function longname = varname2longname(varname)
  % Define Superscript Characters
    sup_minus = char(8315); % ⁻
    sup_1     = char(185);  % ¹
    sup_2     = char(178);  % ²
    
    % Construct Unit Strings
    unit_wm2  = " [W m" + sup_minus + sup_2 + "]";  % [W m⁻²]
    unit_kgm2 = " [kg m" + sup_minus + sup_2 + "]"; % [kg m⁻²]
    unit_ms1  = " [m s" + sup_minus + sup_1 + "]";  % [m s⁻¹]
    
    keys = [
        "dlw", ...
        "dsw", ...
        "rh", ...
        "T_air", ...
        "P", ...
        "V", ...
        "e_air", ...
        "p_air"
    ];
    
    values = [
        "downward logwave radiation" + unit_wm2, ...
        "downward shortwave radiation" + unit_wm2, ...
        "screen level relative humidity [%]", ...
        "screen level air temperature [K]", ...
        "precipitation" + unit_kgm2, ...
        "screen level wind speed" + unit_ms1, ...
        "vapor pressure [Pa]", ...
        "screen level air pressure [Pa]"
    ];
    
    % Create the dictionary
    var_defs = dictionary(keys, values);
    
    longname = var_defs(varname);
end